import { View, Text, StyleSheet } from '@react-pdf/renderer'
import type { FooterBlock } from '@coagent/shared'
import type { BrandPalette } from '../theme'

export function FooterPdf({ block, palette }: { block: FooterBlock; palette: BrandPalette }) {
  const styles = StyleSheet.create({
    wrap: {
      marginTop: 12,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: palette.primarySoft,
      borderTopStyle: 'solid',
    },
    text: { fontSize: 9, color: '#9ca3af', textAlign: 'center' },
  })
  return (
    <View style={styles.wrap} wrap={false}>
      <Text style={styles.text}>{block.note || 'Generated by CoAgent'}</Text>
    </View>
  )
}
