name = "coagent-relay"
main = "src/index.ts"
compatibility_date = "2026-03-01"

[[kv_namespaces]]
binding = "TOKENS"
id = "8d749fb9446e41eb987d9d6f39a72486"

[[durable_objects.bindings]]
name = "USER_SESSION"
class_name = "UserSession"

[[durable_objects.bindings]]
name = "TEAM_CHANNEL"
class_name = "TeamChannel"

[[migrations]]
tag = "v3"
new_sqlite_classes = ["UserSession"]

[[migrations]]
tag = "v4"
new_sqlite_classes = ["TeamChannel"]
